name: Validate the Packer AMI Template
on:
  pull_request:
    branches: [main]
jobs:      
  packer_init_validate:
    runs-on: ubuntu-latest
    name: Validate Packer for the AMI Build
    steps: 
      - name: Step 1 - Checkout code from branch
        uses: actions/checkout@v2

      - name: Step 2 - zip all the webService files
        run: |
          zip -r webApp.zip ./
          pwd ./webApp

      - name: Step 3 - Packer Init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: webApp.pkr.hcl

      - name: Step 4 - Validate Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: webApp.pkr.hcl

      - name: Check Packer Template Formatting
        run: |
            if ! packer fmt -check webApp.pkr.hcl; then
            echo "Packer template is not formatted correctly. Please format using 'packer fmt ami.pkr.hcl' and re-push."
            exit 1
            fi